// <auto-generated />
using System;
using EduConnect.Infrastructure.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduConnect.Infrastructure.Migrations
{
    [DbContext(typeof(EduConnectDBContext))]
    [Migration("20250528064333_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduConnect.Domain.Entities.Class", b =>
                {
                    b.Property<int>("ClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClassId"));

                    b.Property<int?>("HomeroomTeacherId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("ClassId")
                        .HasName("PK__Classes__FDF47986186AEB79");

                    b.HasIndex("HomeroomTeacherId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Logbook", b =>
                {
                    b.Property<int>("LogbookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("logbook_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogbookId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.HasKey("LogbookId")
                        .HasName("PK__Logbooks__BC3134B957A16F3C");

                    b.HasIndex("ClassId");

                    b.ToTable("Logbooks");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.LogbookDetail", b =>
                {
                    b.Property<int>("LogbookId")
                        .HasColumnType("int")
                        .HasColumnName("logbook_id");

                    b.Property<int>("PeriodId")
                        .HasColumnType("int")
                        .HasColumnName("period_id");

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.HasKey("LogbookId", "PeriodId")
                        .HasName("PK__LogbookD__EE030A5D08C92B3A");

                    b.HasIndex("ClassId");

                    b.HasIndex("PeriodId");

                    b.ToTable("LogbookDetails");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("message_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<bool?>("HandledByAi")
                        .HasColumnType("bit")
                        .HasColumnName("handled_by_ai");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("receiver_id");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("sender_id");

                    b.Property<DateTime?>("Timestamp")
                        .HasColumnType("datetime")
                        .HasColumnName("timestamp");

                    b.HasKey("MessageId")
                        .HasName("PK__Messages__0BBF6EE67C8C6D13");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<string>("Frequency")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("frequency");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("receiver_id");

                    b.Property<string>("SenderId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("sender_id");

                    b.Property<string>("SummaryText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary_text");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__E059842F697ED848");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Parent", b =>
                {
                    b.Property<int>("ParentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParentId"));

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("ParentId")
                        .HasName("PK__Parents__F2A60819723CD93F");

                    b.HasIndex(new[] { "UserId" }, "UQ__Parents__B9BE370EB755D0D6")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Period", b =>
                {
                    b.Property<int>("PeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("period_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeriodId"));

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("LessonIndex")
                        .HasColumnType("int")
                        .HasColumnName("lesson_index");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.Property<int?>("TimetableId")
                        .HasColumnType("int")
                        .HasColumnName("timetable_id");

                    b.HasKey("PeriodId")
                        .HasName("PK__Periods__2323EE447251A0A4");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TimetableId");

                    b.ToTable("Periods");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Reminder", b =>
                {
                    b.Property<int>("ReminderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("reminder_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReminderId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<int?>("TeacherId")
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    b.HasKey("ReminderId")
                        .HasName("PK__Reminder__E27A36289EFE8297");

                    b.HasIndex("ClassId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("StudentId")
                        .HasName("PK__Students__2A33069A6EC149E2");

                    b.HasIndex("ClassId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.StudentNote", b =>
                {
                    b.Property<int>("StudentnoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("studentnote_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentnoteId"));

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<int?>("LogbookId")
                        .HasColumnType("int")
                        .HasColumnName("logbook_id");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("StudentnoteId")
                        .HasName("PK__StudentN__3761597A823180CC");

                    b.HasIndex("LogbookId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentNote", (string)null);
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("subject_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubjectId"));

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("SubjectId")
                        .HasName("PK__Subjects__5004F6606DE4F4AE");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Teacher", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("teacher_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_id");

                    b.HasKey("TeacherId")
                        .HasName("PK__Teachers__03AE777ED45D85B1");

                    b.HasIndex(new[] { "UserId" }, "UQ__Teachers__B9BE370EEC85B5FA")
                        .IsUnique()
                        .HasFilter("[user_id] IS NOT NULL");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Timetable", b =>
                {
                    b.Property<int>("TimetableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("timetable_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimetableId"));

                    b.Property<int?>("ClassId")
                        .HasColumnType("int")
                        .HasColumnName("class_id");

                    b.HasKey("TimetableId")
                        .HasName("PK__Timetabl__26DC9588E42104A6");

                    b.HasIndex("ClassId");

                    b.ToTable("Timetables");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ParentStudent", b =>
                {
                    b.Property<int>("ParentId")
                        .HasColumnType("int")
                        .HasColumnName("parent_id");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.HasKey("ParentId", "StudentId")
                        .HasName("PK__ParentSt__40053870CEC99380");

                    b.HasIndex("StudentId");

                    b.ToTable("ParentStudent", (string)null);
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Class", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Teacher", "HomeroomTeacher")
                        .WithMany("Classes")
                        .HasForeignKey("HomeroomTeacherId")
                        .HasConstraintName("FK__Classes__Homeroo__440B1D61");

                    b.Navigation("HomeroomTeacher");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Logbook", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Class", "Class")
                        .WithMany("Logbooks")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Logbooks__class___571DF1D5");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.LogbookDetail", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Class", "Class")
                        .WithMany("LogbookDetails")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__LogbookDe__class__5AEE82B9");

                    b.HasOne("EduConnect.Domain.Entities.Logbook", "Logbook")
                        .WithMany("LogbookDetails")
                        .HasForeignKey("LogbookId")
                        .IsRequired()
                        .HasConstraintName("FK__LogbookDe__logbo__59FA5E80");

                    b.HasOne("EduConnect.Domain.Entities.Period", "Period")
                        .WithMany("LogbookDetails")
                        .HasForeignKey("PeriodId")
                        .IsRequired()
                        .HasConstraintName("FK__LogbookDe__perio__5BE2A6F2");

                    b.Navigation("Class");

                    b.Navigation("Logbook");

                    b.Navigation("Period");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Message", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.User", "Receiver")
                        .WithMany("MessageReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Messages__receiv__6B24EA82");

                    b.HasOne("EduConnect.Domain.Entities.User", "Sender")
                        .WithMany("MessageSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__Messages__sender__6A30C649");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Notification", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.User", "Receiver")
                        .WithMany("NotificationReceivers")
                        .HasForeignKey("ReceiverId")
                        .HasConstraintName("FK__Notificat__recei__6754599E");

                    b.HasOne("EduConnect.Domain.Entities.User", "Sender")
                        .WithMany("NotificationSenders")
                        .HasForeignKey("SenderId")
                        .HasConstraintName("FK__Notificat__sende__66603565");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Parent", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.User", "User")
                        .WithOne("Parent")
                        .HasForeignKey("EduConnect.Domain.Entities.Parent", "UserId")
                        .HasConstraintName("FK__Parents__user_id__412EB0B6");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Period", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Subject", "Subject")
                        .WithMany("Periods")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__Periods__subject__5441852A");

                    b.HasOne("EduConnect.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Periods")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__Periods__teacher__534D60F1");

                    b.HasOne("EduConnect.Domain.Entities.Timetable", "Timetable")
                        .WithMany("Periods")
                        .HasForeignKey("TimetableId")
                        .HasConstraintName("FK__Periods__timetab__52593CB8");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");

                    b.Navigation("Timetable");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Reminder", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Class", "Class")
                        .WithMany("Reminders")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Reminders__class__6383C8BA");

                    b.HasOne("EduConnect.Domain.Entities.Teacher", "Teacher")
                        .WithMany("Reminders")
                        .HasForeignKey("TeacherId")
                        .HasConstraintName("FK__Reminders__teach__628FA481");

                    b.Navigation("Class");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Student", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Students__class___46E78A0C");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.StudentNote", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Logbook", "Logbook")
                        .WithMany("StudentNotes")
                        .HasForeignKey("LogbookId")
                        .HasConstraintName("FK__StudentNo__logbo__5FB337D6");

                    b.HasOne("EduConnect.Domain.Entities.Student", "Student")
                        .WithMany("StudentNotes")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__StudentNo__stude__5EBF139D");

                    b.Navigation("Logbook");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Teacher", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("EduConnect.Domain.Entities.Teacher", "UserId")
                        .HasConstraintName("FK__Teachers__user_i__3D5E1FD2");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Timetable", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Class", "Class")
                        .WithMany("Timetables")
                        .HasForeignKey("ClassId")
                        .HasConstraintName("FK__Timetable__class__4F7CD00D");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduConnect.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ParentStudent", b =>
                {
                    b.HasOne("EduConnect.Domain.Entities.Parent", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .IsRequired()
                        .HasConstraintName("FK__ParentStu__paren__49C3F6B7");

                    b.HasOne("EduConnect.Domain.Entities.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK__ParentStu__stude__4AB81AF0");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Class", b =>
                {
                    b.Navigation("LogbookDetails");

                    b.Navigation("Logbooks");

                    b.Navigation("Reminders");

                    b.Navigation("Students");

                    b.Navigation("Timetables");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Logbook", b =>
                {
                    b.Navigation("LogbookDetails");

                    b.Navigation("StudentNotes");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Period", b =>
                {
                    b.Navigation("LogbookDetails");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Student", b =>
                {
                    b.Navigation("StudentNotes");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Subject", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Teacher", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Periods");

                    b.Navigation("Reminders");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.Timetable", b =>
                {
                    b.Navigation("Periods");
                });

            modelBuilder.Entity("EduConnect.Domain.Entities.User", b =>
                {
                    b.Navigation("MessageReceivers");

                    b.Navigation("MessageSenders");

                    b.Navigation("NotificationReceivers");

                    b.Navigation("NotificationSenders");

                    b.Navigation("Parent");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
