// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using EduConnect.Domain.Entities;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using EduConnect.Domain.Enums;

namespace EduConnect.Infrastructure.DBContext;

public partial class EduConnectDBContext : IdentityDbContext<User>
{
    public EduConnectDBContext()
    {
    }

    public EduConnectDBContext(DbContextOptions<EduConnectDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Class> Classes { get; set; }

    public virtual DbSet<Logbook> Logbooks { get; set; }

    public virtual DbSet<LogbookDetail> LogbookDetails { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Parent> Parents { get; set; }

    public virtual DbSet<Period> Periods { get; set; }

    public virtual DbSet<Reminder> Reminders { get; set; }

    public virtual DbSet<Student> Students { get; set; }

    public virtual DbSet<StudentNote> StudentNotes { get; set; }

    public virtual DbSet<Subject> Subjects { get; set; }

    public virtual DbSet<Teacher> Teachers { get; set; }

    public virtual DbSet<Timetable> Timetables { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=PHUOCWS\\SQLEXPRESS;Initial Catalog=EduConnectDB;User ID=sa;Password=12;Encrypt=False");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
		base.OnModelCreating(modelBuilder);

		modelBuilder.Entity<Class>(entity =>
        {
            entity.HasKey(e => e.ClassId).HasName("PK__Classes__FDF47986186AEB79");

            entity.Property(e => e.ClassId).HasColumnName("class_id");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");

            entity.HasOne(d => d.HomeroomTeacher).WithMany(p => p.Classes)
                .HasForeignKey(d => d.HomeroomTeacherId)
                .HasConstraintName("FK__Classes__Homeroo__440B1D61");
        });

        modelBuilder.Entity<Logbook>(entity =>
        {
            entity.HasKey(e => e.LogbookId).HasName("PK__Logbooks__BC3134B957A16F3C");

            entity.Property(e => e.LogbookId).HasColumnName("logbook_id");
            entity.Property(e => e.ClassId).HasColumnName("class_id");

            entity.HasOne(d => d.Class).WithMany(p => p.Logbooks)
                .HasForeignKey(d => d.ClassId)
                .HasConstraintName("FK__Logbooks__class___571DF1D5");
        });

        modelBuilder.Entity<LogbookDetail>(entity =>
        {
            entity.HasKey(e => new { e.LogbookId, e.PeriodId }).HasName("PK__LogbookD__EE030A5D08C92B3A");

            entity.Property(e => e.LogbookId).HasColumnName("logbook_id");
            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.ClassId).HasColumnName("class_id");
            entity.Property(e => e.Note).HasColumnName("note");

            entity.HasOne(d => d.Class).WithMany(p => p.LogbookDetails)
                .HasForeignKey(d => d.ClassId)
                .HasConstraintName("FK__LogbookDe__class__5AEE82B9");

            entity.HasOne(d => d.Logbook).WithMany(p => p.LogbookDetails)
                .HasForeignKey(d => d.LogbookId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LogbookDe__logbo__59FA5E80");

            entity.HasOne(d => d.Period).WithMany(p => p.LogbookDetails)
                .HasForeignKey(d => d.PeriodId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LogbookDe__perio__5BE2A6F2");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Messages__0BBF6EE67C8C6D13");

            entity.Property(e => e.MessageId).HasColumnName("message_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.HandledByAi).HasColumnName("handled_by_ai");
            entity.Property(e => e.ReceiverId).HasColumnName("receiver_id");
            entity.Property(e => e.SenderId).HasColumnName("sender_id");
            entity.Property(e => e.Timestamp)
                .HasColumnType("datetime")
                .HasColumnName("timestamp");

            entity.HasOne(d => d.Receiver).WithMany(p => p.MessageReceivers)
                .HasForeignKey(d => d.ReceiverId)
                .HasConstraintName("FK__Messages__receiv__6B24EA82");

            entity.HasOne(d => d.Sender).WithMany(p => p.MessageSenders)
                .HasForeignKey(d => d.SenderId)
                .HasConstraintName("FK__Messages__sender__6A30C649");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__E059842F697ED848");

            entity.Property(e => e.NotificationId).HasColumnName("notification_id");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Frequency)
                .HasMaxLength(50)
                .HasColumnName("frequency");
            entity.Property(e => e.ReceiverId).HasColumnName("receiver_id");
            entity.Property(e => e.SenderId).HasColumnName("sender_id");
            entity.Property(e => e.SummaryText).HasColumnName("summary_text");

            entity.HasOne(d => d.Receiver).WithMany(p => p.NotificationReceivers)
                .HasForeignKey(d => d.ReceiverId)
                .HasConstraintName("FK__Notificat__recei__6754599E");

            entity.HasOne(d => d.Sender).WithMany(p => p.NotificationSenders)
                .HasForeignKey(d => d.SenderId)
                .HasConstraintName("FK__Notificat__sende__66603565");
        });

        modelBuilder.Entity<Parent>(entity =>
        {
            entity.HasKey(e => e.ParentId).HasName("PK__Parents__F2A60819723CD93F");

            entity.HasIndex(e => e.UserId, "UQ__Parents__B9BE370EB755D0D6").IsUnique();

            entity.Property(e => e.ParentId).HasColumnName("parent_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithOne(p => p.Parent)
                .HasForeignKey<Parent>(d => d.UserId)
                .HasConstraintName("FK__Parents__user_id__412EB0B6");

            entity.HasMany(d => d.Students).WithMany(p => p.Parents)
                .UsingEntity<Dictionary<string, object>>(
                    "ParentStudent",
                    r => r.HasOne<Student>().WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ParentStu__stude__4AB81AF0"),
                    l => l.HasOne<Parent>().WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK__ParentStu__paren__49C3F6B7"),
                    j =>
                    {
                        j.HasKey("ParentId", "StudentId").HasName("PK__ParentSt__40053870CEC99380");
                        j.ToTable("ParentStudent");
                        j.IndexerProperty<int>("ParentId").HasColumnName("parent_id");
                        j.IndexerProperty<int>("StudentId").HasColumnName("student_id");
                    });
        });

        modelBuilder.Entity<Period>(entity =>
        {
            entity.HasKey(e => e.PeriodId).HasName("PK__Periods__2323EE447251A0A4");

            entity.Property(e => e.PeriodId).HasColumnName("period_id");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.LessonIndex).HasColumnName("lesson_index");
            entity.Property(e => e.SubjectId).HasColumnName("subject_id");
            entity.Property(e => e.TeacherId).HasColumnName("teacher_id");
            entity.Property(e => e.TimetableId).HasColumnName("timetable_id");

            entity.HasOne(d => d.Subject).WithMany(p => p.Periods)
                .HasForeignKey(d => d.SubjectId)
                .HasConstraintName("FK__Periods__subject__5441852A");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Periods)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK__Periods__teacher__534D60F1");

            entity.HasOne(d => d.Timetable).WithMany(p => p.Periods)
                .HasForeignKey(d => d.TimetableId)
                .HasConstraintName("FK__Periods__timetab__52593CB8");
        });

        modelBuilder.Entity<Reminder>(entity =>
        {
            entity.HasKey(e => e.ReminderId).HasName("PK__Reminder__E27A36289EFE8297");

            entity.Property(e => e.ReminderId).HasColumnName("reminder_id");
            entity.Property(e => e.ClassId).HasColumnName("class_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.Date).HasColumnName("date");
            entity.Property(e => e.TeacherId).HasColumnName("teacher_id");

            entity.HasOne(d => d.Class).WithMany(p => p.Reminders)
                .HasForeignKey(d => d.ClassId)
                .HasConstraintName("FK__Reminders__class__6383C8BA");

            entity.HasOne(d => d.Teacher).WithMany(p => p.Reminders)
                .HasForeignKey(d => d.TeacherId)
                .HasConstraintName("FK__Reminders__teach__628FA481");
        });

        modelBuilder.Entity<Student>(entity =>
        {
            entity.HasKey(e => e.StudentId).HasName("PK__Students__2A33069A6EC149E2");

            entity.Property(e => e.StudentId).HasColumnName("student_id");
            entity.Property(e => e.ClassId).HasColumnName("class_id");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");

            entity.HasOne(d => d.Class).WithMany(p => p.Students)
                .HasForeignKey(d => d.ClassId)
                .HasConstraintName("FK__Students__class___46E78A0C");
        });

        modelBuilder.Entity<StudentNote>(entity =>
        {
            entity.HasKey(e => e.StudentnoteId).HasName("PK__StudentN__3761597A823180CC");

            entity.ToTable("StudentNote");

            entity.Property(e => e.StudentnoteId).HasColumnName("studentnote_id");
            entity.Property(e => e.Content).HasColumnName("content");
            entity.Property(e => e.LogbookId).HasColumnName("logbook_id");
            entity.Property(e => e.StudentId).HasColumnName("student_id");

            entity.HasOne(d => d.Logbook).WithMany(p => p.StudentNotes)
                .HasForeignKey(d => d.LogbookId)
                .HasConstraintName("FK__StudentNo__logbo__5FB337D6");

            entity.HasOne(d => d.Student).WithMany(p => p.StudentNotes)
                .HasForeignKey(d => d.StudentId)
                .HasConstraintName("FK__StudentNo__stude__5EBF139D");
        });

        modelBuilder.Entity<Subject>(entity =>
        {
            entity.HasKey(e => e.SubjectId).HasName("PK__Subjects__5004F6606DE4F4AE");

            entity.Property(e => e.SubjectId).HasColumnName("subject_id");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
        });

        modelBuilder.Entity<Teacher>(entity =>
        {
            entity.HasKey(e => e.TeacherId).HasName("PK__Teachers__03AE777ED45D85B1");

            entity.HasIndex(e => e.UserId, "UQ__Teachers__B9BE370EEC85B5FA").IsUnique();

            entity.Property(e => e.TeacherId).HasColumnName("teacher_id");
            entity.Property(e => e.UserId).HasColumnName("user_id");

            entity.HasOne(d => d.User).WithOne(p => p.Teacher)
                .HasForeignKey<Teacher>(d => d.UserId)
                .HasConstraintName("FK__Teachers__user_i__3D5E1FD2");
        });

        modelBuilder.Entity<Timetable>(entity =>
        {
            entity.HasKey(e => e.TimetableId).HasName("PK__Timetabl__26DC9588E42104A6");

            entity.Property(e => e.TimetableId).HasColumnName("timetable_id");
            entity.Property(e => e.ClassId).HasColumnName("class_id");

            entity.HasOne(d => d.Class).WithMany(p => p.Timetables)
                .HasForeignKey(d => d.ClassId)
                .HasConstraintName("FK__Timetable__class__4F7CD00D");
        });

		modelBuilder.Entity<IdentityRole>()
	    .HasData(SeedingRoles());

		modelBuilder.Entity<User>()
			.HasData(SeedingUsers());

		modelBuilder.Entity<IdentityUserRole<string>>()
			.HasData(SeedingUserRoles());

		OnModelCreatingPartial(modelBuilder);
    }

	private ICollection<IdentityRole> SeedingRoles()
	{
		return new List<IdentityRole>()
		{
			new IdentityRole()
			{
				Id = "3631e38b-60dd-4d1a-af7f-a26f21c2ef82",
				Name = Domain.Enums.Roles.Admin.ToString().ToLower(),
				NormalizedName = Domain.Enums.Roles.Admin.ToString().ToUpper(),
				ConcurrencyStamp = "3631e38b-60dd-4d1a-af7f-a26f21c2ef82"
			},
			new IdentityRole()
			{
				Id = "51ef7e08-ff07-459b-8c55-c7ebac505103",
				Name = Domain.Enums.Roles.Teacher.ToString().ToLower(),
				NormalizedName = Domain.Enums.Roles.Teacher.ToString().ToUpper(),
				ConcurrencyStamp = "51ef7e08-ff07-459b-8c55-c7ebac505103"
			},
			new IdentityRole()
			{
				Id = "37a7c5df-4898-4fd4-8e5f-d2abd4b57520",
				Name = Domain.Enums.Roles.Parent.ToString().ToLower(),
				NormalizedName = Domain.Enums.Roles.Parent.ToString().ToUpper(),
				ConcurrencyStamp = "37a7c5df-4898-4fd4-8e5f-d2abd4b57520"
			}
		};
	}

	private ICollection<User> SeedingUsers()
	{
		var hasher = new PasswordHasher<User>();
		return new List<User>()
		{
			new User()
			{
				Id = "a1b2c3d4-e5f6-7890-abcd-123456789012",
				UserName = "admin",
				NormalizedUserName = "ADMIN",
				Email = "admin@example.com",
				NormalizedEmail = "ADMIN@EXAMPLE.COM",
				EmailConfirmed = true,
				PasswordHash = hasher.HashPassword(new User(), "12345aA@"),
				SecurityStamp = Guid.NewGuid().ToString(),
				ConcurrencyStamp = Guid.NewGuid().ToString()
			},
			new User()
			{
				Id = "b2c3d4e5-f6a7-8901-bcde-234567890123",
				UserName = "teacher",
				NormalizedUserName = "TEACHER",
				Email = "teacher@example.com",
				NormalizedEmail = "TEACHER@EXAMPLE.COM",
				EmailConfirmed = true,
				PasswordHash = hasher.HashPassword(new User(), "12345aA@"),
                SecurityStamp = Guid.NewGuid().ToString(),
				ConcurrencyStamp = Guid.NewGuid().ToString()
			},
			new User()
			{
				Id = "c3d4e5f6-a789-0123-cdef-345678901234",
				UserName = "parent",
				NormalizedUserName = "PARENT",
				Email = "parent@example.com",
				NormalizedEmail = "PARENT@EXAMPLE.COM",
				EmailConfirmed = true,
				PasswordHash = hasher.HashPassword(new User(), "12345aA@"),
				SecurityStamp = Guid.NewGuid().ToString(),
				ConcurrencyStamp = Guid.NewGuid().ToString()
			}
		};
	}

	private ICollection<IdentityUserRole<string>> SeedingUserRoles()
	{
		return new List<IdentityUserRole<string>>()
		{
			new IdentityUserRole<string>()
			{
				UserId = "a1b2c3d4-e5f6-7890-abcd-123456789012",
				RoleId = "3631e38b-60dd-4d1a-af7f-a26f21c2ef82"
			},
			new IdentityUserRole<string>()
			{
				UserId = "b2c3d4e5-f6a7-8901-bcde-234567890123",
				RoleId = "51ef7e08-ff07-459b-8c55-c7ebac505103"
			},
			new IdentityUserRole<string>()
			{
				UserId = "c3d4e5f6-a789-0123-cdef-345678901234",
				RoleId = "37a7c5df-4898-4fd4-8e5f-d2abd4b57520"
			}
		};
	}

	partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}