// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Class
{
    public int ClassId { get; set; }

    public string Name { get; set; }

    public int? HomeroomTeacherId { get; set; }

    public virtual Teacher HomeroomTeacher { get; set; }

    public virtual ICollection<LogbookDetail> LogbookDetails { get; set; } = new List<LogbookDetail>();

    public virtual ICollection<Logbook> Logbooks { get; set; } = new List<Logbook>();

    public virtual ICollection<Reminder> Reminders { get; set; } = new List<Reminder>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<Timetable> Timetables { get; set; } = new List<Timetable>();
}