// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class LogbookDetail
{
    public int LogbookId { get; set; }

    public int? ClassId { get; set; }

    public int PeriodId { get; set; }

    public string Note { get; set; }

    public virtual Class Class { get; set; }

    public virtual Logbook Logbook { get; set; }

    public virtual Period Period { get; set; }
}