// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Logbook
{
    public int LogbookId { get; set; }

    public int? ClassId { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<LogbookDetail> LogbookDetails { get; set; } = new List<LogbookDetail>();

    public virtual ICollection<StudentNote> StudentNotes { get; set; } = new List<StudentNote>();
}