// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Message
{
    public int MessageId { get; set; }

    public string SenderId { get; set; } = string.Empty;

    public string ReceiverId { get; set; } = string.Empty;

    public string Content { get; set; }

    public DateTime? Timestamp { get; set; }

    public bool? HandledByAi { get; set; }

    public virtual User Receiver { get; set; }

    public virtual User Sender { get; set; }
}