// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Notification
{
    public int NotificationId { get; set; }

    public string SenderId { get; set; } = string.Empty;

	public string ReceiverId { get; set; } = string.Empty;

	public string SummaryText { get; set; }

    public string Frequency { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual User Receiver { get; set; }

    public virtual User Sender { get; set; }
}