// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Parent
{
    public int ParentId { get; set; }

    public string UserId { get; set; } = string.Empty;

    public virtual User User { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}