// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Period
{
    public int PeriodId { get; set; }

    public int? TimetableId { get; set; }

    public int? TeacherId { get; set; }

    public int? SubjectId { get; set; }

    public DateOnly? Date { get; set; }

    public int? LessonIndex { get; set; }

    public virtual ICollection<LogbookDetail> LogbookDetails { get; set; } = new List<LogbookDetail>();

    public virtual Subject Subject { get; set; }

    public virtual Teacher Teacher { get; set; }

    public virtual Timetable Timetable { get; set; }
}