// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Reminder
{
    public int ReminderId { get; set; }

    public int? TeacherId { get; set; }

    public int? ClassId { get; set; }

    public DateOnly? Date { get; set; }

    public string Content { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual Class Class { get; set; }

    public virtual Teacher Teacher { get; set; }
}