// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Student
{
    public int StudentId { get; set; }

    public int? ClassId { get; set; }

    public string Name { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<StudentNote> StudentNotes { get; set; } = new List<StudentNote>();

    public virtual ICollection<Parent> Parents { get; set; } = new List<Parent>();
}