// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class StudentNote
{
    public int StudentnoteId { get; set; }

    public int? StudentId { get; set; }

    public int? LogbookId { get; set; }

    public string Content { get; set; }

    public virtual Logbook Logbook { get; set; }

    public virtual Student Student { get; set; }
}