// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Subject
{
    public int SubjectId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Period> Periods { get; set; } = new List<Period>();
}