// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Teacher
{
    public int TeacherId { get; set; }

    public string UserId { get; set; } = string.Empty;

    public virtual ICollection<Class> Classes { get; set; } = new List<Class>();

    public virtual ICollection<Period> Periods { get; set; } = new List<Period>();

    public virtual ICollection<Reminder> Reminders { get; set; } = new List<Reminder>();

    public virtual User User { get; set; }
}