// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class Timetable
{
    public int TimetableId { get; set; }

    public int? ClassId { get; set; }

    public virtual Class Class { get; set; }

    public virtual ICollection<Period> Periods { get; set; } = new List<Period>();
}