// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace EduConnect.Domain.Entities;

public partial class User : IdentityUser
{
    public string RefeshToken { get; set; } = string.Empty;

    public DateTime RefeshTokenExpiryTime { get; set; } = DateTime.UtcNow.AddDays(7);

	public bool IsActive { get; set; } = true;

	public virtual ICollection<Message> MessageReceivers { get; set; } = new List<Message>();

    public virtual ICollection<Message> MessageSenders { get; set; } = new List<Message>();

    public virtual ICollection<Notification> NotificationReceivers { get; set; } = new List<Notification>();

    public virtual ICollection<Notification> NotificationSenders { get; set; } = new List<Notification>();

    public virtual Parent Parent { get; set; }

    public virtual Teacher Teacher { get; set; }
}